---

- name: analyzer_runner | Download 
  get_url: 
    url="{{sonar_analyzer_runner_url}}"
    dest="/tmp/{{sonar_analyzer_runner_file}}"
  tags: analyzer_runner

- name: analyzer_runner | Create base dir 
  file: 
    dest="{{sonar_analyzer_runner_dir}}"
    state=directory
    owner="{{sonar_owner}}"
    group="{{sonar_group}}"
  tags: analyzer_runner

- name: analyzer_runner | Extract archive
  unarchive: 
    src="/tmp/{{sonar_analyzer_runner_file}}"
    dest="{{sonar_base_dir}}/"
    owner="{{sonar_owner}}"
    group="{{sonar_group}}"
    copy=no
    creates="{{sonar_analyzer_runner_dir}}/conf"
  sudo_user: "{{sonar_owner}}"
  tags: analyzer_runner
  notify: restart sonar

- name: analyzer_runner | Configuration file
  template:
    src=sonar-runner.properties.j2
    dest="{{sonar_analyzer_runner_dir}}/conf/sonar-runner.properties"
  tags: analyzer_runner
  notify: restart sonar

- name: analyzer_runner | bash profile SONAR_RUNNER_HOME
  lineinfile: 
     dest="{{sonar_base_dir}}/.bash_profile" 
     state=present
     create=yes
     regexp="SONAR_RUNNER_HOME"
     line="export SONAR_RUNNER_HOME={{sonar_analyzer_runner_dir}}"
     mode=0644
     owner="{{sonar_owner}}"
     group="{{sonar_group}}"
  tags: analyzer_runner

- name: analyzer_runner | bash profile PATH
  lineinfile: 
     dest="{{sonar_base_dir}}/.bash_profile" 
     state=present
     create=yes
     regexp="PATH"
     line="export PATH=$PATH:{{sonar_analyzer_runner_dir}}/bin"
     mode=0644
     owner="{{sonar_owner}}"
     group="{{sonar_group}}"
  tags: analyzer_runner