---

  
- name: mysql | Create sonar mysql database
  mysql_db: >
    name={{ sonar_jdbc_db }}
    state=present
    login_user={{ sonar_login_user}}    
    login_password={{ sonar_login_password }}
  sudo_user: "{{ sonar_mysql_sudo_user }}"
  notify: restart sonar
  tags: mysql_server
  
- name: mysql | Create sonar mysql user
  mysql_user: >
    name={{ sonar_jdbc_user }}
    host={{ item }}
    priv={{ sonar_jdbc_db }}.*:ALL
    password={{ sonar_jdbc_pass }}
    login_user={{ sonar_login_user}}    
    login_password={{ sonar_login_password }}    
  with_items: sonar_mysql_allowed_hosts
  sudo_user: "{{ sonar_mysql_sudo_user }}"
  notify: restart sonar
  tags: mysql_server      
 
